[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools >= 61.0",
]

[project]
name = "sthali-db"
version = "0.1.0"
authors = [
  { name = "Jhunu Fernandes", email = "jhunu.fernandes@gmail.com" },
]
description = "A FastAPI package dependency for SthaliCRUD perform DB queries"
readme = "README.md"
requires-python = ">= 3.11"
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Internet",
  "Topic :: Software Development :: Libraries :: Application Frameworks",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development",
  "Typing :: Typed",
]
dependencies = [
  "pydantic",
  "sqlalchemy",
]

[project.urls]
"Homepage" = "https://github.com/jhunufernandes/sthali-db"
"Bug Tracker" = "https://github.com/jhunufernandes/sthali-db/issues"
"Source" = "https://github.com/jhunufernandes/sthali-db"
"Documentation" = "https://jhunufernandes.github.io/sthali-db"
"Changelog" = "https://github.com/jhunufernandes/sthali-db/releases"

[project.optional-dependencies]
dev = [
  "coverage[toml] >= 7.9.1",
  "ruff >= 0.12.0",
]
tests = [
  "coverage[toml] >= 7.9.1",
]
stage = [
  "build >= 1.2.1",
  "coverage[toml] >= 7.9.1",
]

[tool.ruff]
line-length = 119

[tool.ruff.lint]
select = [
  "ALL",
]
ignore = [
  "ANN401",  # any-type
  "ANN003",  # missing-type-kwargs
  "ANN002",  # missing-type-args
  "TID252",  # relative-imports
]

[tool.ruff.lint.per-file-ignores]
"src/sthali_crud/routers/api.py" = [
  "D417",  # undocumented-param
]
"src/sthali_crud/routers/views.py" = [
  "D417",  # undocumented-param
]

"tests/*" = [
  "COM812",  # missing-trailing-comma
  "D100",  # undocumented-public-module
  "D101",  # undocumented-public-class
  "D102",  # undocumented-public-method
  "D104",  # undocumented-public-package
  "D106",  # undocumented-public-nested-class
  "PIE804",  # unnecessary-dict-kwargs
  "PT009",  # pytest-unittest-assertion
  "PT027",  # pytest-unittest-raises-assertion
]

[tool.ruff.lint.pydocstyle]
convention = "google"
