nav:
- Home: index.md
- Requirements: requirements.md
- Installation: installation.md
- Usage: usage.md
- About:
  - License: license.md
  - Release Notes: https://github.com/project-sthali/sthali-db/releases
  - Issue Tracker: https://github.com/project-sthali/sthali-db/issues
- API Reference:
  - DB: api/class_DB.md
  - DBSpecification: api/class_DBSpecification.md
  - FieldSpecification: api/class_FieldSpecification.md
  - Models: api/class_Models.md
  - PaginateParameters: api/class_PaginateParameters.md
  - Types: api/class_Types.md
repo_name: sthali-db
repo_url: https://github.com/project-sthali/sthali-db/
site_author: Jhunu Fernandes
site_description: A FastAPI package dependency for SthaliCRUD perform DB queries
site_name: sthali-db
site_url: https://project-sthali.github.io/sthali-db/
theme: readthedocs
