edit_uri: blob/main/docs/docs/
nav:
- Home: index.md
- Requirements: requirements.md
- Installation: installation.md
- Usage: usage.md
- API Reference:
  - DB.md: api/DB.md
  - DBSpecification.md: api/DBSpecification.md
  - FieldSpecification.md: api/FieldSpecification.md
  - Models.md: api/Models.md
  - PaginateParameters.md: api/PaginateParameters.md
  - dependencies.md: api/dependencies.md
- About:
  - License: license.md
  - Release Notes: https://github.com/jhunufernandes/sthali-db/pulls?q=is%3Apr+is%3Aclosed+release
  - Issue Tracker: https://github.com/jhunufernandes/sthali-db/issues
repo_name: sthali-db
repo_url: https://github.com/jhunufernandes/sthali-db/
site_author: '{{cookiecutter.full_name}}'
site_description: '{{cookiecutter.project_short_description}}'
site_name: sthali-db
site_url: https://jhunufernandes.github.io/sthali-db/
theme: readthedocs
