name: deploy
on:
  push:
    branches:
      - main
jobs:
  install-deps:
    uses: project-sthali/sthali-core/.github/workflows/deps.yml@main
    with:
      pip_args: stage
  run-deploy:
    needs:
      - install-deps
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: python-deps-stage
          path: .
      - run: |
          unzip venv.zip
      - run: |
          .venv/bin/python -m build -o ./dist
      - uses: pypa/gh-action-pypi-publish@release/v1
