name: trigger-tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - development
jobs:
  run-tests:
    uses: project-sthali/sthali-core/.github/workflows/run-tests.yml@development
